version: '2.2'
services:
  influx:
    image: influxdb
    environment:
      - INFLUXDB_DB=weather
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=user
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    ports:
      - 8086:8086
    networks:
      - weather
  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    ports:
    - 3000:3000
    networks:
      - weather
  jupiter:
    image: jupyter/scipy-notebook:63d0df23b673
    command:
      start.sh jupyter notebook --NotebookApp.token=''
    ports:
      - 127.0.0.1:8888:8888
    networks:
      - weather
networks:
  weather:
    driver: bridge
